version: '3.1'
services:
  camunda:
    image: camunda/camunda-bpm-platform:latest
    links:
      - "db:db"
    ports:
      - "8080:8080"
    environment:
      - DB_DRIVER=org.postgresql.Driver
      - DB_URL=jdbc:postgresql://db:5432/camunda
      - DB_USERNAME=camunda
      - DB_PASSWORD=camunda
      - WAIT_FOR=db:5432
      - WAIT_FOR_TIMEOUT=60
  db:
    image: postgres
    environment:
        - POSTGRES_USER=camunda
        - POSTGRES_PASSWORD=camunda
    ports:
        - 5432:5432
